annotations:
  artifacthub.io/changes: |
    - "[Changed]: Restore RBAC permissions and clarify namespace settings."
apiVersion: v2
appVersion: v3.2.3 # 0.8.1 helm 에는 v3.2.0 이였음. 해당 버전에 버그가 있어서 v3.2.3 으로 수정함
description: A Helm chart for Argo Workflows
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo-workflows/master/docs/assets/argo.png
maintainers:
- name: alexec
- name: alexmt
- name: jessesuen
- name: benjaminws
name: argo-workflows
sources:
- https://github.com/argoproj/argo-workflows
type: application
version: 0.8.1
