apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.common.name }}-{{ now | date "20060102150405" }}
  # generateName: {{ .Values.common.name }}-
  annotations:
    argocd.argoproj.io/hook: Sync
  labels:
    app: {{ .Values.common.name }}
    {{- with .Values.common.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.job.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      name: {{ .Values.common.name }}
    spec:
      containers:
      - name: {{ .Values.common.name }}
        image: {{ .Values.job.image }}
        command: 
        {{- with .Values.job.command }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        args: 
        {{- with .Values.job.args }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      restartPolicy: Never
  backoffLimit: 3