common:
  name: hcp-test-job-new1
  labels:
    prjName: hcp-test

job:
  image: perl
  labels:
    jobName: hcp-test-job-new1
  command:
    - perl
  args:
    - -Mbignum=bpi
    - -wle
    - print bpi(2000)
