apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.common.name }}
    {{- with .Values.common.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
