apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}
  labels:
    app: {{ .Values.common.name }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.common.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.common.name }}
        {{- with .Values.common.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        {{- with .Values.deployment.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.resources }}
        resources: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- with .Values.deployment.volumeMounts }}
          {{- toYaml . | nindent 8}}
        {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      {{- with .Values.deployment.volumes }}
        {{- toYaml . | nindent 6}}
      {{- end }}
      {{- with .Values.deployment.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
