# Source: jupyterlab/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
  labels:
    app: {{ .Values.common.name }}
    {{- with .Values.common.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: port0
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    prjName: {{ .Values.common.labels.prjName }}
    svcname: {{ .Values.common.labels.svcName }}