common:
  name: hcp-test1-job001
  labels:
    prjName: hcp-test1
    svcName: hcp-test1-job001
    rscType: job
    rscSubType: none

job:
  image: perl
  labels: {}
  command:
    - perl
  args:
    - -Mbignum=bpi
    - -wle
    - print bpi(2000)