apiVersion: v1
entries:
  app:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-30T13:42:23.623121+09:00"
    description: A Helm chart for DWP App. Service
    digest: 8b89091e041f699742975c077959d8c362cd7fc61b4592803a1220aaeff12b37
    name: app
    type: application
    urls:
    - app-1.0.0.tgz
    version: 1.0.0
  fastapi:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-30T13:42:23.623984+09:00"
    description: A Helm chart for fastapi (python)
    digest: 0ab8fd18b4da4f2c34943f50175d974a9315e2462cc04e70cb44052ef2d056d3
    name: fastapi
    type: application
    urls:
    - fastapi-1.0.0.tgz
    version: 1.0.0
  job:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2021-11-30T13:42:23.624702+09:00"
    description: A Helm chart for job
    digest: d07beff104a2ff6a11e76c6c839a1f1979b3eb4508047ad3425774756b7a6d26
    name: job
    type: application
    urls:
    - job-1.0.0.tgz
    version: 1.0.0
  jupyterlab:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2021-11-30T13:42:23.625529+09:00"
    description: A Helm chart for DWP DS Service
    digest: f96cba82216c1e8c8f8a8909b95ac9ffb86aef646890591f9b188140a77be9f8
    name: jupyterlab
    type: application
    urls:
    - jupyterlab-1.0.0.tgz
    version: 1.0.0
  project:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-30T13:42:23.625928+09:00"
    description: A Helm chart for project
    digest: d94e6c1eef60d5619bda3396a928cc4a14915f324e05a54816b636ccdd7c6f37
    name: project
    type: application
    urls:
    - project-1.0.0.tgz
    version: 1.0.0
  pvc:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2021-11-30T13:42:23.626685+09:00"
    description: A Helm chart for pvc
    digest: e36f8672cc4d08b3ca0040ad5be0f4c6fa449748d7e07d31cd1e430246e4f869
    name: pvc
    type: application
    urls:
    - pvc-1.0.0.tgz
    version: 1.0.0
  python-backend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-30T13:42:23.627583+09:00"
    description: A Helm chart for python-backend
    digest: abb617af890f537a068097b1db08bfe93ed70e88502e2f84dc6c050a5ed4aecb
    name: python-backend
    type: application
    urls:
    - python-backend-1.0.0.tgz
    version: 1.0.0
generated: "2021-11-30T13:42:23.621606+09:00"
