apiVersion: v1
entries:
  app:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-29T10:39:17.03166+09:00"
    description: A Helm chart for DWP App. Service
    digest: 8b89091e041f699742975c077959d8c362cd7fc61b4592803a1220aaeff12b37
    name: app
    type: application
    urls:
    - app-1.0.0.tgz
    version: 1.0.0
  fastapi:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-29T10:39:17.032139+09:00"
    description: A Helm chart for fastapi (python)
    digest: 0ab8fd18b4da4f2c34943f50175d974a9315e2462cc04e70cb44052ef2d056d3
    name: fastapi
    type: application
    urls:
    - fastapi-1.0.0.tgz
    version: 1.0.0
  job:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2021-11-29T10:39:17.032499+09:00"
    description: A Helm chart for job
    digest: d07beff104a2ff6a11e76c6c839a1f1979b3eb4508047ad3425774756b7a6d26
    name: job
    type: application
    urls:
    - job-1.0.0.tgz
    version: 1.0.0
  jupyterlab:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2021-11-29T10:39:17.03299+09:00"
    description: A Helm chart for DWP DS Service
    digest: 0626f23639e22476884b1f9cdc7809a00b91e73578d8af0ec3bd030bb2176fec
    name: jupyterlab
    type: application
    urls:
    - jupyterlab-1.0.0.tgz
    version: 1.0.0
  project:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-29T10:39:17.033237+09:00"
    description: A Helm chart for project
    digest: 870b24c36f6baa2d5c7cd4114b40c1cd2abb37a7f2c41ba8b2b88e45c075861e
    name: project
    type: application
    urls:
    - project-1.0.0.tgz
    version: 1.0.0
  pvc:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2021-11-29T10:39:17.03354+09:00"
    description: A Helm chart for pvc
    digest: 2c82fe4cc73196859c35ac172e80958ff539e02b651e790413e787c1dfa9cdd1
    name: pvc
    type: application
    urls:
    - pvc-1.0.0.tgz
    version: 1.0.0
  python-backend:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-11-29T10:39:17.034034+09:00"
    description: A Helm chart for python-backend
    digest: abb617af890f537a068097b1db08bfe93ed70e88502e2f84dc6c050a5ed4aecb
    name: python-backend
    type: application
    urls:
    - python-backend-1.0.0.tgz
    version: 1.0.0
generated: "2021-11-29T10:39:17.030984+09:00"
