common:
  name: hcp-sre-jupyter-lab
  labels:
    prjName: hcp-sre-cq
    svcName: hcp-sre-jupyter-lab
    rscType: app
    rscSubType: fastapi
    locId: hcpcq-aws

deployment:
  replicas: 1
  image: harbor.hcpcq.kubepia.net/kmchoi-test/jupyterlab
  resources: 
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi

service:
  enabled: true
  type: ClusterIP # ClusterIP, NodePort
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  host: hcp-sre-jupyter-lab.hcpcq.kubepia.net
  path: /
  serviceName: hcp-sre-jupyter-lab
  servicePort: 8000