common:
  name: hcp-test-jupyterlab
  labels:
    prjName: hcp-test
    svcName: jupyterlab
    rscType: helm
    rscSubType: jupyterlab
    locId: hcpcq-aws

deployment:
  replicas: 1
  image: harbor.hcpcq.kubepia.net/kmchoi-test/jupyterlab
  resources: 
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi

service:
  enabled: true
  type: ClusterIP # ClusterIP, NodePort
  port: 8888
  targetPort: 8888

ingress:
  enabled: true
  host: hcp-test-jupyterlab.hcpcq.kubepia.net
  path: /
  serviceName: jupyterlab
  servicePort: 8888