apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.common.name }}
  labels:
    app: {{ .Values.common.name }}
    {{- with .Values.common.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.pvc.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
  {{- with .Values.pvc.accessModes }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
