apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.common.name }}
  # generateName: {{ .Values.common.name }}-
  annotations:
    argocd.argoproj.io/hook: Sync
  labels:
    app: {{ .Values.common.name }}
    {{- with .Values.common.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.job.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.common.name }}
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure