---
# Source: argocd-project/templates/argocd-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-git-hcp-test1
  namespace: hcp-sre-argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/hcp-sre-cq/hcp-sre-cluster-deploy.git
    path: hcpcq-aws/hcp-test1
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: hcp-sre-argocd
  revisionHistoryLimit: 10
  # syncPolicy:
  #   syncOptions:
  #     - CreateNamespace=true
